<p><p> V&#352;EOBECN&Eacute; ZMLUVN&Eacute; PODMIENKY CK FREIBUS SLOVAKIA Tour (dalej len FST) V&#353;eobecn&eacute; zmluvn&eacute; podmienky &uacute;&#269;asti na z&aacute;jazdoch cestovnej kancel&aacute;rie FST a reklama&#269;n&yacute; poriadok (&#271;alej len VZP obstar&aacute;vate&#318;a) s&uacute; platn&eacute; pre v&#353;etky z&aacute;jazdy, pobyty a slu&#382;by cestovn&eacute;ho ruchu organizovan&eacute; cestovnou kancel&aacute;riou FST. V&#353;eobecn&eacute; podmienky CK FST s&uacute; neoddelite&#318;nou s&uacute;&#269;as&#357;ou Zmluvy o obstaran&iacute; z&aacute;jazdu, ktor&uacute; CK FST uzatv&aacute;ra s objedn&aacute;vate&#318;om z&aacute;jazdu. Podpisom zmluvy alebo zaplaten&iacute;m z&aacute;lohy za dohodnut&eacute; slu&#382;by objedn&aacute;vate&#318; potvrdzuje, &#382;e tieto inform&aacute;cie a podmienky s&uacute; mu zn&aacute;me, uzn&aacute;va ich a s&uacute;hlas&iacute; s nimi.</p>

<p>VZNIK ZMLUVN&Eacute;HO VZ&#356;AHU A OBJEDN&Aacute;VKA Z&Aacute;JAZDU RESP. REZERV&Aacute;CIA Z&Aacute;JAZDU 1.1. &Uacute;&#269;astn&iacute;kmi zmluvn&eacute;ho vz&#357;ahu s&uacute;: Cestovn&aacute; kancel&aacute;ria Freibus SLOVAKIA Tour, s r.o. so s&iacute;dlom na n&aacute;m. &#317;.&#352;t&uacute;ra 2357, 955 01 Topo&#318;&#269;anoch (&#271;alej len obstar&aacute;vate&#318;), ktor&aacute; do zmluvn&eacute;ho vz&#357;ahu vstupuje prostredn&iacute;ctvom extern&yacute;ch autorizovan&yacute;ch predajcov (&#271;alej iba CK (cestovn&aacute; kancel&aacute;ria) resp. CA (cestovn&aacute; agent&uacute;ra)) alebo siete vlastn&yacute;ch predajn&yacute;ch miest a objedn&aacute;vate&#318;, ktor&yacute;m m&ocirc;&#382;e by&#357; fyzick&aacute; alebo pr&aacute;vnick&aacute; osoba.</p>

<p>1.2. Zmluvn&yacute; vz&#357;ah medzi obstar&aacute;vate&#318;om a objedn&aacute;vate&#318;om vznik&aacute; uzatvoren&iacute;m zmluvy o obstaran&iacute; z&aacute;jazdu, t.j. prijat&iacute;m objedn&aacute;vate&#318;om podp&iacute;sanej zmluvy o z&aacute;jazde a jej potvrden&iacute;m zo strany CK. Zmluva o z&aacute;jazde plat&iacute; pre v&#353;etky &#271;al&#353;ie osoby na nej uveden&eacute;. Za plnenie zmluvn&yacute;ch z&aacute;v&auml;zkov os&ocirc;b uveden&yacute;ch v zmluve ru&#269;&iacute; objedn&aacute;vate&#318; ako za plnenie svojich vlastn&yacute;ch z&aacute;v&auml;zkov. Za neplnolet&uacute; osobu podpisuje zmluvu jej z&aacute;konn&yacute; z&aacute;stupca. Osoby do 18 rokov m&ocirc;&#382;u cestova&#357; len v sprievode dospel&yacute;ch os&ocirc;b alebo s p&iacute;somn&yacute;m s&uacute;hlasom z&aacute;konn&eacute;ho z&aacute;stupcu. Ak vek klienta prekro&#269;il 65 rokov, alebo je v lek&aacute;rskej starostlivosti odpor&uacute;&#269;ame mu poradi&#357; sa s lek&aacute;rom. V pr&iacute;pade dlhodob&eacute;ho u&#382;&iacute;vania liekov (napr. inzul&iacute;nu), je potrebn&eacute; vzia&#357; si so sebou dostato&#269;n&uacute; z&aacute;sobu liekov. Pri v&#353;etk&yacute;ch z&aacute;jazdoch do klimaticky a epidemiologicky n&aacute;ro&#269;n&yacute;ch oblast&iacute; je &uacute;&#269;as&#357; klienta na z&aacute;jazde podmienen&aacute; predlo&#382;en&iacute;m lek&aacute;rskeho potvrdenia o zdravotnej sp&ocirc;sobilosti.</p>

<p>1.3. Obsah Zml&uacute;v o z&aacute;jazde sa ur&#269;uje pod&#318;a katal&oacute;gu, cenn&iacute;ka a dodato&#269;n&yacute;ch pon&uacute;k obstar&aacute;vate&#318;a, z&aacute;kazn&iacute;kom potvrden&yacute;ch objedn&aacute;vok, t&yacute;chto V&#353;eobecn&yacute;ch podmienok, pr&iacute;p. osobitn&yacute;ch podmienok prilo&#382;en&yacute;ch k zmluve o z&aacute;jazde.</p>

<p>1.4. Potvrden&iacute;m zmluvy o obstaran&iacute; z&aacute;jazdu sa obstar&aacute;vate&#318; objedn&aacute;vate&#318;ovi zav&auml;zuje zabezpe&#269;i&#357; slu&#382;by v dohodnutom rozsahu, kvalite a v s&uacute;lade s dohodnut&yacute;mi podmienkami.</p>

<p>1.5. Rezerv&aacute;cia miest - rezervova&#357; miesta v ur&#269;itom z&aacute;jazde je mo&#382;n&eacute; telefonicky (d&#314;&#382;ka rezerv&aacute;cie max. 3 pracovn&eacute; dni) alebo osobne. Ak nie je vo v&yacute;nimo&#269;n&yacute;ch pr&iacute;padoch dohodnut&eacute; inak. Obstar&aacute;vate&#318; m&aacute; pr&aacute;vo zru&#353;i&#357; rezerv&aacute;ciu pokia&#318; prihl&aacute;&#353;ka na z&aacute;jazd nebola doru&#269;en&aacute; do CK najnesk&ocirc;r do 7 pracovn&yacute;ch dn&iacute; odo d&#328;a rezervovania miest.</p>

<p>PLATOBN&Eacute; PODMIENKY 2.1. Z&aacute;loha za z&aacute;jazd - Obstar&aacute;vate&#318; je opr&aacute;vnen&yacute; po&#382;adova&#357; od objedn&aacute;vate&#318;a z&aacute;lohu vo v&yacute;&#353;ke 50 % z dohodnutej ceny a to najnesk&ocirc;r do 3 pracovn&yacute;ch dn&iacute; odo d&#328;a podp&iacute;sania zmluvy o obstaran&iacute; z&aacute;jazdu. Pokia&#318; obstar&aacute;vate&#318; neobdr&#382;&iacute; z&aacute;lohu od objedn&aacute;vate&#318;a v dohodnutom term&iacute;ne, obstar&aacute;vate&#318; je opr&aacute;vnen&yacute; zru&#353;i&#357; zmluvu resp. rezerv&aacute;ciu miest bez &#271;al&#353;ieho upom&iacute;nania objedn&aacute;vate&#318;a.</p>

<p>2.2. Doplatok za z&aacute;jazd - Doplatok dohodnutej ceny slu&#382;ieb je objedn&aacute;vate&#318; povinn&yacute; zaplati&#357; obstar&aacute;vate&#318;ovi najnesk&ocirc;r 30 dn&iacute; pred dohodnut&yacute;m term&iacute;nom poskytovanej slu&#382;by.</p>

<p>2.3. V pr&iacute;pade vzniku zmluvn&eacute;ho vz&#357;ahu v lehote krat&#353;ej ako 30 dn&iacute; pred za&#269;iatkom z&aacute;jazdu je objedn&aacute;vate&#318; povinn&yacute; ihne&#271; uhradi&#357; 100 % ceny dosia&#318; objednan&yacute;ch slu&#382;ieb, ak nebolo dohodnut&eacute; inak.</p>

<p>2.4. Objedn&aacute;vate&#318; m&aacute; n&aacute;rok na poskytnutie slu&#382;ieb len po zaplaten&iacute; celej ceny objednan&yacute;ch slu&#382;ieb. V pr&iacute;pade, &#382;e objedn&aacute;vate&#318; z ak&yacute;chko&#318;vek d&ocirc;vodov nedodr&#382;&iacute; spl&aacute;tkov&yacute; kalend&aacute;r &uacute;hrady dosia&#318; objednan&yacute;ch slu&#382;ieb, je obstar&aacute;vate&#318; opr&aacute;vnen&yacute; odst&uacute;pi&#357; od uzavretej zmluvy o z&aacute;jazde a po&#382;adova&#357; zaplatenie zmluvnej pokuty pod&#318;a &#269;l&aacute;nku 7 VZP obstar&aacute;vate&#318;a.</p>

<p>CENA 3.1. Ceny z&aacute;jazdov obstar&aacute;vate&#318;a s&uacute; zmluvn&yacute;mi cenami dohodnut&yacute;mi p&iacute;somnou dohodou medzi obstar&aacute;vate&#318;om a objedn&aacute;vate&#318;om. Z&aacute;v&auml;zn&aacute; a dohodnut&aacute; cena je uveden&aacute; v Zmluve o obstaran&iacute; z&aacute;jazdu. V cenn&iacute;ku obstar&aacute;vate&#318;a s&uacute; uveden&eacute; orienta&#269;n&eacute; ceny. Pre ur&#269;enie cien z&aacute;jazdov, slu&#382;ieb a poplatkov bol pou&#382;it&yacute; kurz meny platnej v SR oproti cudz&iacute;m men&aacute;m pod&#318;a ofici&aacute;lneho kurzov&eacute;ho l&iacute;stka NBS zo d&#328;a uvedenom v cenn&iacute;ku.</p>

<p>3.2. Obstar&aacute;vate&#318; je opr&aacute;vnen&yacute; jednostranne zv&yacute;&#353;i&#357; dohodnut&uacute; cenu slu&#382;ieb v pr&iacute;pade, &#382;e d&ocirc;jde k:</p>

<p>a.) zv&yacute;&#353;eniu dopravn&yacute;ch n&aacute;kladov (vr&aacute;tane cien pohonn&yacute;ch l&aacute;tok),</p>

<p>b.) zv&yacute;&#353;eniu poplatkov spojen&yacute;ch s dopravou (napr. letiskov&eacute; poplatky, dopravn&eacute; poistenie, pr&iacute;stavn&eacute; poplatky a dia&#318;ni&#269;n&eacute; poplatky zahrnut&eacute; v cene z&aacute;jazdu),</p>

<p>c.) zmene kurzu meny platnej v SR pou&#382;it&eacute;ho na ur&#269;enie dohodnutej ceny v priemere o viac ako 5%, ak k tomuto zv&yacute;&#353;eniu d&ocirc;jde do 21. D&#328;a pred dohodnut&yacute;m term&iacute;nom poskytnutia slu&#382;by.</p>

<p>3.3. Ak d&ocirc;jde k uveden&yacute;m zmen&aacute;m do 21. d&#328;a pred za&#269;iatkom z&aacute;jazdu, je obstar&aacute;vate&#318; opr&aacute;vnen&yacute; cenu z&aacute;jazdu uveden&uacute; v Zmluve o z&aacute;jazde jednostranne zv&yacute;&#353;i&#357; o &#269;iastku, o ktor&uacute; sa zv&yacute;&#353;i cena alebo platba pod&#318;a odst. 2) p&iacute;smena a) a b) oproti cene slu&#382;ieb a platieb zahrnut&yacute;ch v cene z&aacute;jazdu. V pr&iacute;pade zmeny kurzu meny platnej v SR pou&#382;it&eacute;ho pri kalkul&aacute;cii ceny z&aacute;jazdu v priemere o viac ako 5 % je obstar&aacute;vate&#318; opr&aacute;vnen&yacute; zv&yacute;&#353;i&#357; jednostranne cenu z&aacute;jazdu maxim&aacute;lne o &#269;iastku zodpovedaj&uacute;cu percentu&aacute;lnej v&yacute;&#353;ke zmeny kurzu. Ak d&ocirc;jde k tak&eacute;muto jednostrann&eacute;mu zv&yacute;&#353;eniu ceny, objedn&aacute;vate&#318; m&ocirc;&#382;e od zmluvy odst&uacute;pi&#357; a obstar&aacute;vate&#318; je opr&aacute;vnen&yacute; po&#382;adova&#357; zaplatenie zmluvnej pokuty pod&#318;a &#269;l&aacute;nku 7 VZP obstar&aacute;vate&#318;a.</p>

<p>3.4. P&iacute;somn&eacute; ozn&aacute;menie o zv&yacute;&#353;en&iacute; ceny mus&iacute; obstar&aacute;vate&#318; odosla&#357; objedn&aacute;vate&#318;ovi najnesk&ocirc;r 21 dn&iacute; pred za&#269;iatkom z&aacute;jazdu, inak obstar&aacute;vate&#318;ovi nevznikne pr&aacute;vo na zaplatenie rozdielu v cene z&aacute;jazdu.</p>

<p>4.1. Objedn&aacute;vate&#318; m&aacute; pr&aacute;vo:</p>

<p>a.) na riadne poskytnutie zmluvne dohodnut&yacute;ch a zaplaten&yacute;ch slu&#382;ieb, vy&#382;adova&#357; od obstar&aacute;vate&#318;a inform&aacute;cie o v&#353;etk&yacute;ch skuto&#269;nostiach, ktor&eacute; sa t&yacute;kaj&uacute; zmluvne dohodnut&yacute;ch a zaplaten&yacute;ch slu&#382;ieb,</p>

<p>b.) by&#357; obozn&aacute;men&yacute; v zmluvne dohodnut&yacute;ch alebo z&aacute;konn&yacute;ch lehot&aacute;ch s pr&iacute;padn&yacute;mi zmenami v zmluvne dohodnut&yacute;ch slu&#382;b&aacute;ch, odst&uacute;pi&#357; od zmluvy kedyko&#318;vek pred za&#269;iatkom &#269;erpania slu&#382;ieb pod&#318;a &#269;l&aacute;nku 7 VZP obstar&aacute;vate&#318;a</p>

<p>c.) na reklam&aacute;ciu nedostatkov a jej vybavenie v s&uacute;lade s &#269;l&aacute;nkom 8 VZP obstar&aacute;vate&#318;a</p>

<p>d.) obdr&#382;a&#357; najnesk&ocirc;r 7 dn&iacute; pred za&#269;iatkom z&aacute;jazdu &#271;al&#353;ie p&iacute;somn&eacute; podrobn&eacute; inform&aacute;cie o v&#353;etk&yacute;ch skuto&#269;nostiach, ktor&eacute; s&uacute; pre objedn&aacute;vate&#318;a d&ocirc;le&#382;it&eacute;, a ktor&eacute; s&uacute; obstar&aacute;vate&#318;ovi zn&aacute;me, pokia&#318; nie s&uacute; u&#382; obsiahnut&eacute; v Zmluve o z&aacute;jazde alebo v katal&oacute;gu, ktor&yacute; bol objedn&aacute;vate&#318;ovi odovzdan&yacute;. Tieto p&iacute;somn&eacute; inform&aacute;cie o z&aacute;jazde posiela obstar&aacute;vate&#318; po&#353;tou len na jednu adresu, uveden&uacute; objedn&aacute;vate&#318;om. V pr&iacute;pade, &#382;e 7 dn&iacute; pred odchodom objedn&aacute;vate&#318; e&#353;te tieto inform&aacute;cie o z&aacute;jazde nem&aacute;, je povinn&yacute; bezodkladne o tom informova&#357; cestovn&uacute; kancel&aacute;riu, aby zabezpe&#269;ila n&aacute;pravu. Inak obstar&aacute;vate&#318; pova&#382;uje pokyny za spr&aacute;vne, kompletne a v&#269;as doru&#269;en&eacute; na objedn&aacute;vate&#318;om uveden&uacute; adresu. V pr&iacute;pade predaja prostredn&iacute;ctvom partnerskej CK a CA sa pokyny zasielaj&uacute; na adresu CK alebo CA, pokia&#318; nebolo dohodnut&eacute; inak</p>

<p>e.) p&iacute;somne ozn&aacute;mi&#357; obstar&aacute;vate&#318;ovi pred za&#269;iatkom z&aacute;jazdu, &#382;e z&aacute;jazdu sa namiesto neho z&uacute;&#269;astn&iacute; in&aacute; osoba uveden&aacute; v ozn&aacute;men&iacute;. Toto pr&aacute;vo v&#353;ak m&ocirc;&#382;e objedn&aacute;vate&#318; uplatni&#357; iba v lehote do 3 dn&iacute; pred za&#269;iatkom z&aacute;jazdu, po uplynut&iacute; tejto lehoty toto pr&aacute;vo objedn&aacute;vate&#318;a zanik&aacute;, ozn&aacute;menie mus&iacute; obsahova&#357; aj vyhl&aacute;senie nov&eacute;ho objedn&aacute;vate&#318;a, &#382;e s&uacute;hlas&iacute; s uzatvorenou zmluvou a sp&#314;&#328;a v&#353;etky dohodnut&eacute; podmienky &uacute;&#269;asti na z&aacute;jazde. D&#328;om doru&#269;enia ozn&aacute;menia sa v &#328;om uveden&aacute; osoba st&aacute;va objedn&aacute;vate&#318;om. P&ocirc;vodn&yacute; a nov&yacute; objedn&aacute;vate&#318; spolo&#269;ne a nerozdielne zodpovedaj&uacute; za zaplatenie ceny z&aacute;jazdu a &uacute;hradu z&aacute;kladnej zmluvnej pokuty.</p>

<p>4.2. Objedn&aacute;vate&#318; m&aacute; povinnos&#357;:</p>

<p>a.) poskytn&uacute;&#357; obstar&aacute;vate&#318;ovi potrebn&uacute; s&uacute;&#269;innos&#357; k riadnemu zabezpe&#269;eniu a poskytnutiu slu&#382;ieb, predov&#353;etk&yacute;m pravdivo a &uacute;plne uv&aacute;dza&#357; po&#382;adovan&eacute; &uacute;daje v zmluve o z&aacute;jazde vr&aacute;tane ak&yacute;chko&#318;vek zmien t&yacute;chto &uacute;dajov a predlo&#382;i&#357; &#271;al&#353;ie doklady pod&#318;a po&#382;iadavky obstar&aacute;vate&#318;a, v pr&iacute;pade &#382;e objedn&aacute;vate&#318; neuvedie pravdivo inform&aacute;cie /vek det&iacute; a podobne / a pokia&#318; t&yacute;m d&ocirc;jde k zmene cenovej kalkul&aacute;cie, je povinn&yacute; okam&#382;ite uhradi&#357; rozdiel v cene</p>

<p>b.) zabezpe&#269;i&#357; u os&ocirc;b mlad&#353;&iacute;ch ako 15 rokov sprev&aacute;dzanie a doh&#318;ad dospel&eacute;ho &uacute;&#269;astn&iacute;ka, obdobne zabezpe&#269;i&#357; sprev&aacute;dzanie a doh&#318;ad u os&ocirc;b, ktor&yacute;ch zdravotn&yacute; stav si to vy&#382;aduje</p>

<p>c.) nahl&aacute;si&#357; &uacute;&#269;as&#357; cudz&iacute;ch &#353;t&aacute;tnych pr&iacute;slu&#353;n&iacute;kov</p>

<p>d.) zaplati&#357; cenu z&aacute;jazdu v s&uacute;lade s &#269;l&aacute;nkom 2 a 3 VZP obstar&aacute;vate&#318;a</p>

<p>e.) bez zbyto&#269;n&eacute;ho odkladu oznamova&#357; obstar&aacute;vate&#318;ovi svoje stanovisko k pr&iacute;padn&yacute;m zmen&aacute;m v podmienkach a obsahu dohodnut&yacute;ch slu&#382;ieb</p>

<p>f.) prevzia&#357; od CK doklady potrebn&eacute; na &#269;erpanie slu&#382;ieb</p>

<p>g.) ma&#357; u seba platn&yacute; cestovn&yacute; doklad, pr&iacute;padne v&iacute;zum (pokia&#318; je vy&#382;adovan&eacute;), dodr&#382;iava&#357; coln&eacute; a pasov&eacute; predpisy kraj&iacute;n, do ktor&yacute;ch cestuje. V&#353;etky n&aacute;klady, ktor&eacute; vznikn&uacute; nedodr&#382;an&iacute;m t&yacute;chto predpisov, zn&aacute;&#353;a &uacute;&#269;astn&iacute;k z&aacute;jazdu. Ka&#382;d&yacute; ob&#269;an vr&aacute;tane malolet&eacute;ho die&#357;a&#357;a m&ocirc;&#382;e vycestova&#357; do zahrani&#269;ia len s platn&yacute;m cestovn&yacute;m dokladom. Odpor&uacute;&#269;ame overi&#357; na zastupite&#318;skom &uacute;rade &#353;t&aacute;tu n&aacute;v&#353;tevy, &#269;i okrem cestovn&eacute;ho dokladu nebude vy&#382;adovan&yacute; tie&#382; p&iacute;somn&yacute; s&uacute;hlas rodi&#269;ov (z&aacute;konn&eacute;ho z&aacute;stupcu), v akej forme a jazyku, a &#269;i podpis mus&iacute; by&#357; overen&yacute; not&aacute;rom, alebo je posta&#269;uj&uacute;ci len jednoduch&yacute; s&uacute;hlas rodi&#269;a (z&aacute;konn&eacute;ho z&aacute;stupcu)</p>

<p>h.) splni&#357; o&#269;kovacie, pr&iacute;p. &#271;al&#353;ie zdravotn&eacute; formality, pri cest&aacute;ch do kraj&iacute;n, pre ktor&eacute; s&uacute; stanoven&eacute; medzin&aacute;rodn&yacute;mi zdravotn&iacute;ckymi predpismi</p>

<p>i.) riadi&#357; sa pokynmi sprievodcu, deleg&aacute;ta alebo in&eacute;ho ur&#269;en&eacute;ho z&aacute;stupcu obstar&aacute;vate&#318;a a dodr&#382;iava&#357; stanoven&yacute; program</p>

<p>j.) po&#269;&iacute;na&#357; si tak, aby nedoch&aacute;dzalo k &#353;kod&aacute;m na zdrav&iacute; alebo majetku na &uacute;kor ostatn&yacute;ch z&aacute;kazn&iacute;kov, dod&aacute;vate&#318;ov slu&#382;ieb alebo obstar&aacute;vate&#318;a</p>

<p>k.) dba&#357; o v&#269;asn&eacute; a riadne uplatnenie pr&iacute;padn&yacute;ch n&aacute;rokov vo&#269;i dod&aacute;vate&#318;om slu&#382;ieb pod&#318;a &#269;l&aacute;nku 8 VZP obstar&aacute;vate&#318;a</p>

<p>l.) dostavi&#357; sa na miesto odchodu v stanovenom &#269;ase</p>

<p>PR&Aacute;VA A POVINNOSTI OBSTAR&Aacute;VATE&#317;A 5.1. K pr&aacute;vam a povinnostiam objedn&aacute;vate&#318;a uveden&yacute;m v &#269;l&aacute;nku 4 VZP obstar&aacute;vate&#318;a sa vz&#357;ahuj&uacute; im zodpovedaj&uacute;ce pr&aacute;va a povinnosti obstar&aacute;vate&#318;a.</p>

<p>5.2. Obstar&aacute;vate&#318; je povinn&yacute; pred uzatvoren&iacute;m Zmluvy o z&aacute;jazde presne informova&#357; o v&#353;etk&yacute;ch skuto&#269;nostiach, ktor&eacute; s&uacute; mu zn&aacute;me, a ktor&eacute; m&ocirc;&#382;u ma&#357; vplyv na rozhodnutie z&aacute;ujemcu o k&uacute;pu z&aacute;jazdu.</p>

<p>5.3. Obstar&aacute;vate&#318; nie je povinn&yacute; poskytn&uacute;&#357; objedn&aacute;vate&#318;ovi plnenia nad r&aacute;mec vopred potvrden&yacute;ch a zaplaten&yacute;ch slu&#382;ieb.</p>

<p>5.4. Obstar&aacute;vate&#318; je povinn&yacute; ma&#357; uzatvoren&uacute; Zmluvu o poisten&iacute; z&aacute;jazdov pre pr&iacute;pad &uacute;padku CK, na z&aacute;klade ktorej vznik&aacute; objedn&aacute;vate&#318;ovi pr&aacute;vo na poistn&eacute; plnenie:</p>

<p>a.) v pr&iacute;pade neposkytnutia objednan&eacute;ho a zaplaten&eacute;ho z&aacute;jazdu poistn&eacute; plnenie vo v&yacute;&#353;ke ceny neposkytnut&eacute;ho z&aacute;jazdu, ktor&uacute; objedn&aacute;vate&#318; zaplatil,</p>

<p>b.) v pr&iacute;pade neposkytnutia objedn&aacute;vate&#318;ovi objednanej a zaplatenej dopravy z miesta pobytu v zahrani&#269;&iacute; na &uacute;zemie Slovenskej republiky t. z. uhradenie n&aacute;kladov na t&uacute;to dopravu,</p>

<p>ak je doprava s&uacute;&#269;as&#357;ou z&aacute;jazdu</p>

<p>c.) v pr&iacute;pade nevr&aacute;tenia rozdielu medzi zaplatenou cenou za z&aacute;jazd a cenou &#269;iasto&#269;ne poskytnut&eacute;ho z&aacute;jazdu objedn&aacute;vate&#318;ovi t. z. uhradenie rozdielu v cene medzi skuto&#269;ne poskytnut&yacute;mi slu&#382;bami a zaplatenou cenou z&aacute;jazdu</p>

<p>5.5. Obstar&aacute;vate&#318; je povinn&yacute; odovzda&#357; objedn&aacute;vate&#318;ovi s&uacute;&#269;asne so zmluvou o z&aacute;jazde aj doklady ur&#269;en&eacute; objedn&aacute;vate&#318;ovi, ktor&eacute; musia obsahova&#357; inform&aacute;cie o uzatvorenom povinnom zmluvnom poisten&iacute; z&aacute;jazdu, najm&auml; v&#353;ak ozna&#269;enie pois&#357;ovne, podmienky poistenia a sp&ocirc;sob ozn&aacute;menia poistnej udalosti. N&aacute;roky objedn&aacute;vate&#318;a, ktor&eacute; mu vznikli vo&#269;i obstar&aacute;vate&#318;ovi v d&ocirc;sledku neplnenia Zmluvy o obstaran&iacute; z&aacute;jazdu, prech&aacute;dzaj&uacute; na pois&#357;ov&#328;u, a to a&#382; do v&yacute;&#353;ky plnenia, ktor&eacute; mu pois&#357;ov&#328;a poskytla.</p>

<p>5.6. Obstar&aacute;vate&#318; nezodpoved&aacute; za me&#353;kanie prenajat&eacute;ho dopravn&eacute;ho prostriedku (lietadlo, autobus, vlak). V pr&iacute;pade me&#353;kania dopravn&eacute;ho prostriedku CK postupuje pod&#318;a z&aacute;kona a zmluvy uzatvorenej medzi obstar&aacute;vate&#318;om a prepravcom.</p>

<p>5.7. Obstar&aacute;vate&#318; m&aacute; pr&aacute;vo na odst&uacute;penie od Zmluvy o obstaran&iacute; z&aacute;jazdu s objedn&aacute;vate&#318;om, ktor&yacute; svojim spr&aacute;van&iacute;m a konan&iacute;m znemo&#382;&#328;uje realiz&aacute;ciu z&aacute;jazdu pod&#318;a vopred dohodnut&yacute;ch podmienok, alebo ohrozuje bezpe&#269;nos&#357; ostatn&yacute;ch &uacute;&#269;astn&iacute;kov z&aacute;jazdu. Objedn&aacute;vate&#318; v tak&yacute;chto pr&iacute;padoch nem&aacute; n&aacute;rok na n&aacute;hradu neposkytnut&yacute;ch slu&#382;ieb.</p>

<p>6.1. Ak je obstar&aacute;vate&#318; n&uacute;ten&yacute; pred za&#269;iatkom z&aacute;jazdu zmeni&#357; podstatn&uacute; podmienku zmluvy (napr. term&iacute;n, kvalitu, cenu a rozsah objednan&yacute;ch slu&#382;ieb), obstar&aacute;vate&#318; navrhne objedn&aacute;vate&#318;ovi telefonicky alebo p&iacute;somne zmenu objednan&yacute;ch slu&#382;ieb v zmluve o obstaran&iacute; z&aacute;jazdu dojednan&yacute;ch medzi obstar&aacute;vate&#318;om a objedn&aacute;vate&#318;om a to z&aacute;konom stanovenej lehote t.j. najnesk&ocirc;r 7 dn&iacute; pred za&#269;at&iacute;m &#269;erpania slu&#382;ieb. Z&aacute;rove&#328; obstar&aacute;vate&#318; uvedie nov&uacute; cenu v pr&iacute;pade, ak zmena zmluvy vedie aj k zmene dohodnutej ceny. Objedn&aacute;vate&#318; ozn&aacute;mi obstar&aacute;vate&#318;ovi p&iacute;somne svoje rozhodnutie v lehote ur&#269;enej obstar&aacute;vate&#318;om. Ak objedn&aacute;vate&#318; neozn&aacute;mi obstar&aacute;vate&#318;ovi svoje rozhodnutie k navrhovanej zmene p&iacute;somnou formou v stanovenej lehote obstar&aacute;vate&#318;om, obstar&aacute;vate&#318; uplatn&iacute; zmenu podmienok a rozsahu dohodnut&yacute;ch slu&#382;ieb dojednan&yacute;ch v Zmluve o obstaran&iacute; z&aacute;jazdu a objedn&aacute;vate&#318;ovi zanik&aacute; pr&aacute;vo na uplatnenie reklam&aacute;cie.</p>

<p>6.2. Obstar&aacute;vate&#318; m&aacute; pr&aacute;vo zru&#353;i&#357; z&aacute;jazd, ktor&yacute; je predmetom zmluvn&eacute;ho vz&#357;ahu uzavret&eacute;ho medzi obstar&aacute;vate&#318;om a objedn&aacute;vate&#318;om, ak v lehote do 21 dn&iacute; pred jeho za&#269;iatkom nebude dosiahnut&yacute; minim&aacute;lny po&#269;et &uacute;&#269;astn&iacute;kov z&aacute;jazdu alebo v in&yacute;ch pr&iacute;padoch, ak jeho uskuto&#269;nenie je pre obstar&aacute;vate&#318;a ekonomicky ne&uacute;nosn&eacute;. Obstar&aacute;vate&#318; ozn&aacute;mi p&iacute;somne objedn&aacute;vate&#318;ovi zru&#353;enie z&aacute;jazdu u&#382; pri vzniku predpokladu, najnesk&ocirc;r v&#353;ak v lehote 7 dn&iacute; pred dohodnut&yacute;m term&iacute;nom poskytovania slu&#382;ieb.</p>

<p>6.3. Obstar&aacute;vate&#318; si &#271;alej vyhradzuje pr&aacute;vo zru&#353;i&#357; z&aacute;jazd v d&ocirc;sledku udalost&iacute;, ktor&yacute;m nie je mo&#382;n&eacute; zabr&aacute;ni&#357; ani pri vynalo&#382;en&iacute; v&#353;etk&eacute;ho &uacute;silia, alebo v d&ocirc;sledku neobvykl&yacute;ch a nepredv&iacute;date&#318;n&yacute;ch okolnost&iacute; (&#382;iveln&eacute; pohromy, teroristick&eacute; &uacute;toky a pod.).</p>

<p>6.4. Ak obstar&aacute;vate&#318; odst&uacute;pi od zmluvy z d&ocirc;vodu zru&#353;enia z&aacute;jazdu pred jeho za&#269;iatkom alebo ak objedn&aacute;vate&#318; nes&uacute;hlas&iacute; s navrhovanou zmenou zmluvy pod&#318;a ods. 1, m&aacute; objedn&aacute;vate&#318; pr&aacute;vo &#382;iada&#357;, aby mu obstar&aacute;vate&#318; na z&aacute;klade novej zmluvy poskytol in&yacute; z&aacute;jazd najmenej v kvalite, ktor&aacute; zodpoved&aacute; slu&#382;b&aacute;m dohodnut&yacute;m v p&ocirc;vodnej zmluve, ak obstar&aacute;vate&#318; m&ocirc;&#382;e tak&yacute;to z&aacute;jazd pon&uacute;knu&#357;. Pri uzatvoren&iacute; novej zmluvy sa platby uskuto&#269;nen&eacute; na z&aacute;klade p&ocirc;vodnej zmluvy pova&#382;uj&uacute; za platby pod&#318;a novej zmluvy. Ak je cena nov&eacute;ho z&aacute;jazdu ni&#382;&#353;ia ako u&#382; uskuto&#269;nen&eacute; platby, je obstar&aacute;vate&#318; povinn&yacute; tento rozdiel objedn&aacute;vate&#318;ovi bezodkladne vr&aacute;ti&#357;.</p>

<p>6.5. Na z&aacute;klade individu&aacute;lneho &#382;elania objedn&aacute;vate&#318;a je obstar&aacute;vate&#318; pripraven&yacute;, pokia&#318; je to mo&#382;n&eacute;, urobi&#357; zmeny podmienok dohodnut&yacute;ch v zmluve o obstaran&iacute; z&aacute;jazdu. Vykonanie tak&yacute;chto zmien podlieha zaplateniu z&aacute;kladnej zmluvnej pokuty za jednu zmenu resp. osobu. Ide o zmenu mena &uacute;&#269;astn&iacute;ka, po&#269;tu os&ocirc;b, term&iacute;nu, n&aacute;stupn&eacute;ho miesta, typu ubytovacieho zariadenia a pod. V pr&iacute;pade takejto zmeny po&#382;adovanej v lehote krat&#353;ej ne&#382; 45 dn&iacute; pred za&#269;iatkom z&aacute;jazdu, je tak&aacute;to zmena pova&#382;ovan&aacute; za odst&uacute;penie od zmluvy zo strany objedn&aacute;vate&#318;a a objedn&aacute;vate&#318; je povinn&yacute; zaplati&#357; cestovnej kancel&aacute;rii zmluvn&uacute; pokutu v s&uacute;lade s &#269;l&aacute;nkom 7 VZP obstar&aacute;vate&#318;a.</p>

<p>6.6. Obstar&aacute;vate&#318; si vyhradzuje pr&aacute;vo na drobn&eacute; zmeny v poskytovan&yacute;ch slu&#382;b&aacute;ch (zmena n&aacute;stupn&eacute;ho miesta, trasy, term&iacute;nu, ubytovania, dopravy).</p>

<p>ODST&Uacute;PENIE OD ZMLUVY, ZMLUVN&Aacute; POKUTA 7.1. Obstar&aacute;vate&#318; m&ocirc;&#382;e pred za&#269;iatkom z&aacute;jazdu od zmluvy odst&uacute;pi&#357; len z d&ocirc;vodu zru&#353;enia z&aacute;jazdu alebo z d&ocirc;vodu poru&#353;enia zmluvne dohodnut&yacute;ch povinnost&iacute; objedn&aacute;vate&#318;om. P&iacute;somn&eacute; ozn&aacute;menie o odst&uacute;pen&iacute; od zmluvy s uveden&iacute;m d&ocirc;vodov zasiela obstar&aacute;vate&#318; p&iacute;somne naadresu objedn&aacute;vate&#318;a uveden&uacute; v zmluve o obstaran&iacute; z&aacute;jazdu. Ukon&#269;enie zmluvn&eacute;ho vz&#357;ahu nast&aacute;va d&#328;om doru&#269;enia ozn&aacute;menia.</p>

<p>7.2. V pr&iacute;pade, &#382;e objedn&aacute;vate&#318; odst&uacute;pi od zmluvy, je povinn&yacute; ozn&aacute;mi&#357; to obstar&aacute;vate&#318;ovi p&iacute;somne a z&aacute;rove&#328; zaplati&#357; zmluvn&uacute; pokutu (storno poplatok). &Uacute;&#269;as&#357; je zru&#353;en&aacute; ku d&#328;u, kedy objedn&aacute;vate&#318; p&iacute;somne s podpisom, pod&aacute; zru&#353;enie &uacute;&#269;asti u obstar&aacute;vate&#318;a. Objedn&aacute;vate&#318; m&ocirc;&#382;e odst&uacute;pi&#357; od zmluvy bez udania d&ocirc;vodu. Zmluva o obstaran&iacute; v tom pr&iacute;pade v tejto &#269;asti nezanik&aacute;. V pr&iacute;pade, ak nenast&uacute;pi z&aacute;kazn&iacute;k na z&aacute;jazd, alebo nevy&#269;erp&aacute; slu&#382;bu CK bez predch&aacute;dzaj&uacute;ceho odst&uacute;penia od zmluvy alebo nezabezpe&#269;il spr&aacute;vne &uacute;daje a platn&eacute; doklady k vycestovaniu, je povinn&yacute; uhradi&#357; 100% z vopred stanovenej celkovej ceny (sumy).</p>

<p>7.3. Zmluvn&aacute; pokuta je v pr&iacute;pade odst&uacute;penia:</p>

<p>do 46 dn&iacute; pred dohodnut&yacute;m term&iacute;nom poskytovania slu&#382;ieb obstar&aacute;vate&#318; &uacute;&#269;tuje z&aacute;kladn&uacute; zmluvn&uacute; pokutu:</p>

<p>1.) 30 &euro;/osoba &ndash; autobusov&aacute; a individu&aacute;lna doprava</p>

<p>2.) 50 &euro;/osoba &ndash; leteck&aacute; doprava</p>

<p>od 45 do 31 dn&iacute; pred dohodnut&yacute;m term&iacute;nom poskytovania slu&#382;ieb je zmluvn&aacute; pokuta 25 % z celkovej ceny objednan&yacute;ch slu&#382;ieb</p>

<p>od 30 do 22 dn&iacute; pred dohodnut&yacute;m term&iacute;nom poskytovania slu&#382;ieb je zmluvn&aacute; pokuta 50 % z celkovej ceny objednan&yacute;ch slu&#382;ieb</p>

<p>od 21 do 15 dn&iacute; pred dohodnut&yacute;m term&iacute;nom poskytovania slu&#382;ieb je zmluvn&aacute; pokuta 70 % z celkovej ceny objednan&yacute;ch slu&#382;ieb</p>

<p>od 14 do 7 dn&iacute; pred dohodnut&yacute;m term&iacute;nom poskytovania slu&#382;ieb je zmluvn&aacute; pokuta 90 % z celkovej ceny objednan&yacute;ch slu&#382;ieb</p>

<p>menej ako 7 dn&iacute; pred dohodnut&yacute;m term&iacute;nom poskytovania slu&#382;ieb je zmluvn&aacute; pokuta 100 % z celkovej ceny objednan&yacute;ch slu&#382;ieb</p>

<p>7.4. Obstar&aacute;vate&#318; je povinn&yacute; do 14 dn&iacute; po obdr&#382;an&iacute; p&iacute;somn&eacute;ho zru&#353;enia zmluvy vr&aacute;ti&#357; zaplaten&uacute; sumu objedn&aacute;vate&#318;om, zn&iacute;&#382;en&uacute; o pr&iacute;slu&#353;n&uacute; zmluvn&uacute; pokutu.</p>

<p>7.5. Zmluvn&aacute; pokuta plat&iacute; i pre v&#353;etky ostatn&eacute; zmeny okrem v&yacute;meny cestuj&uacute;ceho, kde obstar&aacute;vate&#318; ma pr&aacute;vo &uacute;&#269;tova&#357; z&aacute;kladn&uacute; zmluvn&uacute; pokutu.</p>

<p>7.6. Ak objedn&aacute;vate&#318; zmen&iacute; rozsah slu&#382;ieb, resp. ak zru&#353;ia z&aacute;jazd iba niektor&eacute; zo spolucestuj&uacute;cich os&ocirc;b a vplyvom zmeny d&ocirc;jde k zmene napr. typu ubytovania at&#271;. a cena slu&#382;ieb sa zmen&iacute;, rozdiel musia zmluvn&eacute; strany vyrovna&#357; v prospech objedn&aacute;vate&#318;a alebo obstar&aacute;vate&#318;a, pri&#269;om osoby ktor&eacute; zru&#353;ili objednan&eacute; slu&#382;by, s&uacute; povinn&eacute; zaplati&#357; zmluvn&uacute; pokutu pod&#318;a &#269;l&aacute;nku 7 odst. 3 VZP obstar&aacute;vate&#318;a.</p>

<p>7.7. Pri ur&#269;en&iacute; po&#269;tu dn&iacute; pre v&yacute;po&#269;et zmluvnej pokuty je rozhoduj&uacute;ci de&#328;, ktor&yacute;m objedn&aacute;vate&#318; odstupuje od zmluvy. Tento de&#328; sa tie&#382; zapo&#269;&iacute;tava do stanoven&eacute;ho po&#269;tu dn&iacute;. Do po&#269;tu dn&iacute; sa nezapo&#269;&iacute;tava de&#328; odjazdu, odletu alebo n&aacute;stupu na z&aacute;jazd</p>

<p>7.8. V pr&iacute;pade, ak suma zmluvnej pokuty je vy&#353;&#353;ia ako suma ktor&aacute; bola uhraden&aacute; obstar&aacute;vate&#318;ovi objedn&aacute;vate&#318;om, objedn&aacute;vate&#318; je povinn&yacute; tento rozdiel ihne&#271; uhradi&#357; obstar&aacute;vate&#318;ovi.</p>

<p>8.1. V pr&iacute;pade, &#382;e rozsah alebo kvalita slu&#382;ieb je ni&#382;&#353;ia, ako bolo dohodnut&eacute; v Zmluve o obstaran&iacute; z&aacute;jazdu, vznik&aacute; objedn&aacute;vate&#318;ovi pr&aacute;vo na reklam&aacute;ciu. Z&aacute;kazn&iacute;k je povinn&yacute; uplatni&#357; pr&aacute;vo na odstr&aacute;nenie chybne poskytnutej slu&#382;by bez zbyto&#269;n&eacute;ho odkladu, a to priamo na mieste u dod&aacute;vate&#318;a slu&#382;by alebo u poveren&eacute;ho z&aacute;stupcu obstar&aacute;vate&#318;a (deleg&aacute;t, sprievodca) tak, aby mohla by&#357; vykonan&aacute; okam&#382;it&aacute; n&aacute;prava. Z&aacute;stupca obstar&aacute;vate&#318;a je povinn&yacute; rozhodn&uacute;&#357; o reklam&aacute;cii ihne&#271;, v r&aacute;mci svojej kompetencie.</p>

<p>8.2. Ak nie je mo&#382;n&eacute; okam&#382;ite vybavi&#357; reklam&aacute;ciu a vykona&#357; n&aacute;pravu, sp&iacute;&#353;e z&aacute;stupca obstar&aacute;vate&#318;a s reklamuj&uacute;cim reklama&#269;n&yacute; protokol s ozna&#269;en&iacute;m z&aacute;jazdu, reklamuj&uacute;cej osoby a predmetu reklam&aacute;cie. Protokol podp&iacute;&#353;e z&aacute;stupca obstar&aacute;vate&#318;a alebo dod&aacute;vate&#318;a slu&#382;by a reklamuj&uacute;ci, ktor&yacute; obdr&#382;&iacute; jeden exempl&aacute;r reklama&#269;n&eacute;ho protokolu. Tento potvrden&yacute; reklama&#269;n&yacute; protokol je z&aacute;kazn&iacute;k povinn&yacute; predlo&#382;i&#357; pri reklam&aacute;cii.</p>

<p>8.3. Svoje n&aacute;roky z reklam&aacute;cie mus&iacute; z&aacute;kazn&iacute;k uplatni&#357; u obstar&aacute;vate&#318;a bez odkladne, najnesk&ocirc;r v&#353;ak do troch mesiacov od skon&#269;enia z&aacute;jazdu, inak pr&aacute;vo zanik&aacute;. Na v&#353;etky reklam&aacute;cie podan&eacute; v s&uacute;lade s uveden&yacute;mi podmienkami, je obstar&aacute;vate&#318; povinn&yacute; odpoveda&#357; p&iacute;somnou formou, a to naj nesk&ocirc;r do 30 dn&iacute; od obdr&#382;ania reklam&aacute;cie.</p>

<p>8.4. Obstar&aacute;vate&#318; zodpoved&aacute; objedn&aacute;vate&#318;ovi za poru&#353;enie z&aacute;v&auml;zkov vypl&yacute;vaj&uacute;cich z uzatvorenej zmluvy bez oh&#318;adu na to, &#269;i tieto z&aacute;v&auml;zky m&aacute; splni&#357; obstar&aacute;vate&#318; alebo in&iacute; dod&aacute;vatelia slu&#382;ieb s v&yacute;nimkou komplexn&eacute;ho cestovn&eacute;ho poistenia vi&#271; &#269;l&aacute;nok 9, ktor&eacute; sa poskytuj&uacute; v r&aacute;mci z&aacute;jazdu. Obstar&aacute;vate&#318; nezodpoved&aacute; za &uacute;rove&#328; cudz&iacute;ch slu&#382;ieb a akci&iacute; mimo r&aacute;mec z&aacute;jazdu, ktor&eacute; si z&aacute;kazn&iacute;k objedn&aacute; na mieste u deleg&aacute;ta, hotela alebo inej organiz&aacute;cie.</p>

<p>8.5. Za predmet reklam&aacute;cie sa nepova&#382;uj&uacute; tak&eacute; &#353;kody a majetkov&eacute; ujmy sp&ocirc;soben&eacute; z&aacute;kazn&iacute;kovi, ktor&eacute; s&uacute; predmetom zmluvnej &uacute;pravy poistn&eacute;ho krytia pois&#357;ovne na z&aacute;klade poistnej zmluvy o cestovnom poisten&iacute;, ani tak&eacute; &#353;kody a majetkov&eacute; ujmy, ktor&eacute; s&uacute; z rozsahu poistn&eacute;ho krytia v&yacute;slovne vy&#328;at&eacute;.</p>

<p>8.6. Ak nastan&uacute; okolnosti, ktor&yacute;ch vznik, priebeh a n&aacute;sledok nie je z&aacute;visl&yacute; na &#269;innosti a postupe obstar&aacute;vate&#318;a alebo okolnosti na strane z&aacute;kazn&iacute;ka, na z&aacute;klade ktor&yacute;ch z&aacute;kazn&iacute;k &uacute;plne alebo z &#269;asti nevyu&#382;ije objednan&eacute;, zaplaten&eacute; a obstar&aacute;vate&#318;om zabezpe&#269;en&eacute; slu&#382;by, nevznik&aacute; z&aacute;kazn&iacute;kovi n&aacute;rok na &uacute;hradu alebo z&#318;avu z ceny t&yacute;chto slu&#382;ieb.</p>

<p>8.7. Obstar&aacute;vate&#318; nezodpoved&aacute; za pr&iacute;padn&eacute; me&#353;kanie dopravn&yacute;ch prostriedkov a upozor&#328;uje na mo&#382;nos&#357; jeho vzniku z d&ocirc;vodov probl&eacute;mov v cestnej prem&aacute;vke a na hrani&#269;n&yacute;ch prechodoch, preplnen&yacute;ch vzdu&#353;n&yacute;ch koridorov, z d&ocirc;vodov nepriazniv&eacute;ho po&#269;asia, pr&iacute;p. z technick&yacute;ch a prev&aacute;dzkov&yacute;ch d&ocirc;vodov. Obstar&aacute;vate&#318; nezodpoved&aacute; za &#353;kody, ktor&eacute; m&ocirc;&#382;u vznikn&uacute;&#357; n&aacute;sledkom me&#353;kania dopravn&eacute;ho prostriedku. V pr&iacute;pade me&#353;kania dopravn&eacute;ho prostriedku z uveden&yacute;ch d&ocirc;vodov vznik&aacute; z&aacute;kazn&iacute;kovi pr&aacute;vo na odst&uacute;penie od zmluvy pod&#318;a bodu 7.3. VZP CK FST.</p>

<p>8.8. Obstar&aacute;vate&#318; nezodpoved&aacute; za &#353;kodu, ktor&uacute; nezavinil ani on, ani jeho dod&aacute;vatelia slu&#382;ieb a &#353;koda bola sp&ocirc;soben&aacute; z&aacute;kazn&iacute;kom, tre&#357;ou osobou, ktor&aacute; nie je spojen&aacute; s poskytovan&iacute;m z&aacute;jazdu alebo udalos&#357;ou, ktorej nebolo mo&#382;n&eacute; zabr&aacute;ni&#357; ani pri vynalo&#382;en&iacute; v&#353;etk&eacute;ho &uacute;silia, alebo v d&ocirc;sledku neobvykl&yacute;ch a nepredv&iacute;date&#318;n&yacute;ch okolnost&iacute;.</p>

<p>8.9. Objedn&aacute;vate&#318;, ktor&yacute; pou&#382;ije vlastn&uacute; dopravu, je s&aacute;m zodpovedn&yacute; za dodr&#382;anie term&iacute;nu n&aacute;stupu a ukon&#269;enia pobytu, ktor&yacute; obstar&aacute;vate&#318; uv&aacute;dza v pokynoch na z&aacute;jazd.</p>

<p>8.10. Za riadne poskytnutie dopravy sa pova&#382;uje aj poskytnutie dopravy so zmenenou trasou, zmenen&yacute;mi prestupn&yacute;mi miestami aj s pr&iacute;padn&yacute;m &#269;asov&yacute;m nes&uacute;ladom jednotliv&yacute;ch liniek. Obstar&aacute;vate&#318; sa v&#353;ak zav&auml;zuje dodr&#382;a&#357; dohodnut&yacute; druh dopravy, zmeni&#357; ho len vo v&yacute;nimo&#269;n&yacute;ch pr&iacute;padoch na n&aacute;klady obstar&aacute;vate&#318;a, a v pr&iacute;pade poskytnutia lacnej&#353;ej dopravy, vr&aacute;ti CK cenov&yacute; rozdiel objedn&aacute;vate&#318;ovi bezodkladne po n&aacute;vrate.</p>

<p>8.11. Zmeny a odch&yacute;lky jednotliv&yacute;ch slu&#382;ieb s&uacute; v nevyhnutn&yacute;ch pr&iacute;padoch mo&#382;n&eacute;. Ide najm&auml; o zmeny miesta odletu, pr&iacute;letu, trasy, leteckej spolo&#269;nosti, medziprist&aacute;tia, typu lietadla, letov&yacute;ch &#269;asov, term&iacute;nu letu, programu z&aacute;jazdu a pod. V pr&iacute;pade vy&#353;&#353;ie uveden&yacute;ch zmien bude obstar&aacute;vate&#318; bez odkladne informova&#357; objedn&aacute;vate&#318;a. Uveden&eacute; zmeny programu nem&ocirc;&#382;u by&#357; predmetom reklam&aacute;cie a obstar&aacute;vate&#318; neru&#269;&iacute; za &#353;kody, ktor&eacute; m&ocirc;&#382;u vznikn&uacute;&#357; z&aacute;kazn&iacute;kovi z t&yacute;chto d&ocirc;vodov, ani nekompenzuje slu&#382;by, ktor&eacute; z t&yacute;chto d&ocirc;vodov ne&#269;erpali.</p>

<p>8.12. Pri posudzovan&iacute; poctu dn&iacute; dovolenky treba po&#269;&iacute;ta&#357; s t&yacute;m, &#382;e do prv&eacute;ho a posledn&eacute;ho d&#328;a &#269;erpania slu&#382;ieb v r&ocirc;znej miere zasahuj&uacute; dopravn&eacute; a ubytovacie slu&#382;by. Aj v pr&iacute;pade obsadenia izby v rann&yacute;ch hodin&aacute;ch sa predch&aacute;dzaj&uacute;ca noc po&#269;&iacute;ta ako poskytnut&eacute; ubytovanie. Obstar&aacute;vate&#318; neru&#269;&iacute; za &#353;kody, ktor&eacute; m&ocirc;&#382;u vznikn&uacute;&#357; objedn&aacute;vate&#318;ovi z t&yacute;chto d&ocirc;vodov a nekompenzuje slu&#382;by, ktor&eacute; sa z t&yacute;chto d&ocirc;vodov ne&#269;erpali.</p>

<p>8.13. Zmeny letov&yacute;ch &#269;asov sa m&ocirc;&#382;u uskuto&#269;ni&#357; aj kr&aacute;tko pred pl&aacute;novan&yacute;m odletom. Obstar&aacute;vate&#318; neru&#269;&iacute; za me&#353;kanie lietadla, resp.za skor&#353;&iacute; odlet alebo pr&iacute;let (z technick&yacute;ch, resp. prev&aacute;dzkov&yacute;ch d&ocirc;vodov, z d&ocirc;vodu nepriazniv&yacute;ch poveternostn&yacute;ch podmienok, pre&#357;a&#382;enia leteck&yacute;ch ciest a pod.) a za &#353;kody t&yacute;m sp&ocirc;soben&eacute;. V pr&iacute;pade ome&#353;kania resp. skor&#353;ieho odletu alebo pr&iacute;letu lietadla vznik&aacute; objedn&aacute;vate&#318;ovi pr&aacute;vo na kompenz&aacute;ciu za dobu &#269;akania na letisku alebo nevy&#269;erpan&eacute; slu&#382;by s&uacute;visiace s pobytom v rozsahu medzin&aacute;rodne platn&yacute;ch predpisov, pri&#269;om n&aacute;hradn&eacute; plnenie poskytuje a za poskytnutie zodpoved&aacute; leteck&aacute; spolo&#269;nos&#357;. Pr&iacute;padn&eacute; neposkytnutie n&aacute;hradn&eacute;ho plnenia zo strany leteckej spolo&#269;nosti nie je d&ocirc;vodom na odst&uacute;penie od zmluvy o z&aacute;jazde.</p>

<p>8.14. Ka&#382;d&yacute; z&aacute;kazn&iacute;k je osobne zodpovedn&yacute; za dodr&#382;iavanie pasov&yacute;ch, dev&iacute;zov&yacute;ch, tranzitn&yacute;ch, zdravotn&yacute;ch, dopravn&yacute;ch a &#271;al&#353;&iacute;ch predpisov Slovenskej republiky ako aj predpisov, z&aacute;konov a zvyklosti krajiny, do ktorej cestuje, resp. cez &#328;u tranzituje. Obstar&aacute;vate&#318; nenesie zodpovednos&#357; za pr&iacute;padn&eacute; probl&eacute;my vzniknut&eacute; neudelen&iacute;m v&iacute;za alebo chybn&yacute;mi &uacute;konmi z&aacute;kazn&iacute;ka. V&#353;etky n&aacute;klady, ktor&eacute; vznikn&uacute; nedodr&#382;an&iacute;m vy&#353;&#353;ie uveden&yacute;ch predpisov s&uacute; na &#357;archu z&aacute;kazn&iacute;ka.</p>

<p>CESTOVN&Eacute; POISTENIE 9.1. Obstar&aacute;vate&#318; je opr&aacute;vnen&yacute; sprostredkova&#357; a uzatv&aacute;ra&#357; zmluvu o komplexnom cestovnom poisten&iacute; pre &uacute;&#269;astn&iacute;kov z&aacute;jazdu na z&aacute;klade zmluvy podp&iacute;sanej medzi obstar&aacute;vate&#318;om a pois&#357;ov&#328;ou. Poistn&aacute; zmluva je s&uacute;&#269;as&#357;ou zmluvy o obstaran&iacute; z&aacute;jazdu. Poistn&aacute; zmluva na zmluve o obstaran&iacute; z&aacute;jazdu zanik&aacute; (neplat&iacute;) v pr&iacute;pade, ak objedn&aacute;vate&#318; ne&#382;iada sprostredkovanie k&uacute;py cestovn&eacute;ho poistenia. V r&aacute;mci rozsahu komplexn&eacute;ho cestovn&eacute;ho poistenia je okrem in&eacute;ho zahrnut&eacute; aj poistenie pre pr&iacute;pad, &#382;e objedn&aacute;vate&#318;ovi vznikn&uacute; n&aacute;klady v s&uacute;vislosti s jeho odst&uacute;pen&iacute;m od zmluvy o obstaran&iacute; z&aacute;jazdu v pr&iacute;pade nehody alebo ochorenia. Obsah a cena komplexn&eacute;ho cestovn&eacute;ho poistenia s&uacute; uveden&eacute; v zmluve o obstaran&iacute; z&aacute;jazdu, presn&yacute; rozsah krytia a podmienky s&uacute; uveden&eacute; v inform&aacute;ci&aacute;ch pois&#357;ovacej spolo&#269;nosti, ktor&eacute; objedn&aacute;vate&#318; obdr&#382;&iacute; od obstar&aacute;vate&#318;a.</p>

<p>9.2. Poistn&yacute; vz&#357;ah vznik&aacute; priamo medzi &uacute;&#269;astn&iacute;kom z&aacute;jazdu a pois&#357;ovacou spolo&#269;nos&#357;ou. V jednan&iacute; o od&#353;kodnen&iacute; poistnej udalosti je pois&#357;ov&#328;a v priamom vz&#357;ahu k &uacute;&#269;astn&iacute;kovi z&aacute;jazdu a obstar&aacute;vate&#318;ovi neprin&aacute;le&#382;&iacute; posudzova&#357; existenciu, pr&iacute;padne v&yacute;&#353;ku uplat&#328;ovan&yacute;ch n&aacute;rokov z tohto vz&#357;ahu.</p>

<p>Z&Aacute;VERE&#268;N&Eacute; USTANOVENIA 10.1. Platnos&#357; t&yacute;chto V&#353;eobecn&yacute;ch zmluvn&yacute;ch podmienok sa vz&#357;ahuje na z&aacute;jazdy a slu&#382;by poskytovan&eacute; obstar&aacute;vate&#318;om po 01.03.2015, ak nie je obstar&aacute;vate&#318;om stanoven&yacute;, &#269;i vopred dohodnut&yacute; rozsah vz&aacute;jomn&yacute;ch pr&aacute;v a povinnost&iacute; inak, a to v&#382;dy p&iacute;somnou formou.</p>

<p>10.2. Objedn&aacute;vate&#318; potvrdzuje podpisom zmluvy o obstaran&iacute; z&aacute;jazdu resp. zaplaten&iacute;m z&aacute;lohy za dojednan&eacute; slu&#382;by v zmluve, &#382;e s&uacute; mu VZP obstar&aacute;vate&#318;a zn&aacute;me, rozumie im, s&uacute;hlas&iacute; s nimi a v plnom rozsahu ich prij&iacute;ma.</p>

<p>10.3. Objedn&aacute;vate&#318; potvrdzuje podpisom zmluvy o obstaran&iacute; z&aacute;jazdu svoj s&uacute;hlas s t&yacute;m, aby CK FST spracov&aacute;vala jeho osobn&eacute; &uacute;daje uveden&eacute; v zmluve o obstaran&iacute; z&aacute;jazdu vr&aacute;tane rodn&eacute;ho &#269;&iacute;sla a &#269;. pasu za &uacute;&#269;elom pon&uacute;kania slu&#382;ieb poskytovan&yacute;ch a sprostredkovan&yacute;ch CK FST a pre akvizi&#269;n&uacute; &#269;innos&#357;. Objedn&aacute;vate&#318; z&aacute;rove&#328; prehlasuje, &#382;e je splnomocnen&yacute; podpisom zmluvy o obstaran&iacute; z&aacute;jazdu udeli&#357; s&uacute;hlas aj na spracovanie osobn&yacute;ch &uacute;dajov v&#353;etk&yacute;ch os&ocirc;b uveden&yacute;ch v Zmluve o obstaran&iacute; z&aacute;jazdu. Poskytovan&eacute; &uacute;daje m&ocirc;&#382;u by&#357; spr&iacute;stupnen&eacute; iba zamestnancom CK FST a &#271;alej osob&aacute;m, ktor&eacute; s&uacute; opr&aacute;vnen&eacute; slu&#382;by zabezpe&#269;ovan&eacute; CK FST pon&uacute;ka&#357; a poskytova&#357;.</p>

<p>10.4. V&#353;etky &uacute;daje a pokyny obsiahnut&eacute; v katal&oacute;gu, let&aacute;koch a cenn&iacute;ku obstar&aacute;vate&#318;a o slu&#382;b&aacute;ch, cen&aacute;ch a cestovn&yacute;ch podmienkach zodpovedaj&uacute; inform&aacute;ci&aacute;m zn&aacute;mym k 01.03.2015 a obstar&aacute;vate&#318; si vyhradzuje pr&aacute;vo ich zmeny do doby uzatvorenia zmluvy o obstaran&iacute; z&aacute;jazdu s objedn&aacute;vate&#318;om.</p>

<p>V pr&iacute;pade, &#382;e &uacute;daje v katal&oacute;gu, let&aacute;koch a v zmluve sa rozch&aacute;dzaj&uacute;, z&aacute;v&auml;zn&yacute;mi s&uacute; &uacute;daje obsiahnut&eacute; v Zmluve o obstaran&iacute; z&aacute;jazdu. Podpisom Zmluvy o obstaran&iacute; z&aacute;jazdu alebo zaplaten&iacute;m z&aacute;lohy za objednan&eacute; slu&#382;by z&aacute;kazn&iacute;k potvrdzuje, &#382;e bol obozn&aacute;men&yacute; so v&#353;eobecn&yacute;mi podmienkami CK Freibus SLOVAKIA Tour, s.r.o., rozumie im, s&uacute;hlas&iacute; s nimi a prij&iacute;ma ich v plnom rozsahu. </p</p>
